#!/bin/bash


# shellcheck disable=SC1090
# Add lib path to the path
LIB_PATH=$(dirname "${BASH_SOURCE[0]}" | realpath "$(</dev/stdin)/../lib")
PATH=$LIB_PATH:$PATH
source bashlib-echo.sh


OUTPUT=$(echo::info "Hello World" 2>&1)
OUTPUT_EXPECTATION="echo_test::main#11: Hello World"
if [ "$OUTPUT" != "$OUTPUT_EXPECTATION" ]; then
  echo "Error"
  echo "<<<<<<<<<<<<<<<<<<<<"
  echo "$OUTPUT"
  echo ">>>>>>>>>>>>>>>>>>>>"
  echo "$OUTPUT_EXPECTATION"
  exit 1
else
  echo "Success"
fi
