#!/bin/bash


# shellcheck disable=SC1090
source "$(libpath echo.sh)"


OUTPUT=$(echo::info "Hello World" 2>&1)
OUTPUT_EXPECTATION="echo_test::main#8: Hello World"
if [ "$OUTPUT" != "$OUTPUT_EXPECTATION" ]; then
  echo "Error"
  echo "<<<<<<<<<<<<<<<<<<<<"
  echo "$OUTPUT"
  echo ">>>>>>>>>>>>>>>>>>>>"
  echo "$OUTPUT_EXPECTATION"
  exit 1
else
  echo "Success"
fi

grep echo_test yolo
